global using RandomRestaurantQuizz.Api;
global using RandomRestaurantQuizz.Api.ApiCachedClient;
global using RandomRestaurantQuizz.Core;
global using RandomRestaurantQuizz.Core.Data;
global using RandomRestaurantQuizz.Core.Photos;
global using RandomRestaurantQuizz.Core.Places;
global using RandomRestaurantQuizz.Core.Places.GoogleApi;
global using RandomRestaurantQuizz.Core.Quizzz.Scores;
global using System.Text.Json;